### ISSUE TITLE
Missing Alt Attribute

### ISSUE THREAD

**Issue by KhairUnNisa10** [ammarazahid/14-may-task#5]
https://github.com/ammarazahid/14-may-task/blob/89e3ea0cf4697c3d74de854222be7c479762d333/index.html#L46

https://github.com/ammarazahid/14-may-task/blob/89e3ea0cf4697c3d74de854222be7c479762d333/index.html#L113

https://github.com/ammarazahid/14-may-task/blob/89e3ea0cf4697c3d74de854222be7c479762d333/index.html#L124

https://github.com/ammarazahid/14-may-task/blob/89e3ea0cf4697c3d74de854222be7c479762d333/index.html#L127

https://github.com/ammarazahid/14-may-task/blob/89e3ea0cf4697c3d74de854222be7c479762d333/index.html#L132

https://github.com/ammarazahid/14-may-task/blob/89e3ea0cf4697c3d74de854222be7c479762d333/index.html#L135

https://github.com/ammarazahid/14-may-task/blob/89e3ea0cf4697c3d74de854222be7c479762d333/index.html#L138

Alt attribute is missing in the image tag.

**Comment by KhairUnNisa10** [comment]
https://github.com/ammarazahid/14-may-task/blob/e5a2abb6e0b296eddf88e1c77de5852bda2b4d4f/index.html#L116

https://github.com/ammarazahid/14-may-task/blob/e5a2abb6e0b296eddf88e1c77de5852bda2b4d4f/index.html#L127

https://github.com/ammarazahid/14-may-task/blob/e5a2abb6e0b296eddf88e1c77de5852bda2b4d4f/index.html#L138

https://github.com/ammarazahid/14-may-task/blob/e5a2abb6e0b296eddf88e1c77de5852bda2b4d4f/index.html#L151

https://github.com/ammarazahid/14-may-task/blob/e5a2abb6e0b296eddf88e1c77de5852bda2b4d4f/index.html#L162

https://github.com/ammarazahid/14-may-task/blob/e5a2abb6e0b296eddf88e1c77de5852bda2b4d4f/index.html#L173

Alt attribute still missing.

**Comment by ammarazahid** [comment]
done#5
