### ISSUE TITLE
First Section

### ISSUE THREAD

**Issue by KhairUnNisa10** [ammarazahid/14-may-task#7]
Give Padding to Increase the Size:
https://github.com/ammarazahid/14-may-task/blob/89e3ea0cf4697c3d74de854222be7c479762d333/index.html#L59-L72
Give padding to increase the size, to top and bottom.

Font-Size:
Increase the font-size.

Center Align:
Center Align the paragraph.

**Comment by KhairUnNisa10** [comment]
Give padding to increase the size, to top and bottom.
Font-Size:
Increase the font-size of the heading.

**Comment by ammarazahid** [comment]
done mam#7
