### ISSUE TITLE
Second Section

### ISSUE THREAD

**Issue by KhairUnNisa10** [ammarazahid/14-may-task#8]
https://github.com/ammarazahid/14-may-task/blob/89e3ea0cf4697c3d74de854222be7c479762d333/index.html#L74

Increase the heading size.

https://github.com/ammarazahid/14-may-task/blob/89e3ea0cf4697c3d74de854222be7c479762d333/index.html#L76-L98

In the p tag, remove the padding and the margin. And text align center the paragraph.

**Comment by ammarazahid** [comment]
done#8
